<testsuite errors="8" failures="0" name="" tests="8" time="0.004">
<testcase classname="unittest.loader._FailedTest" name="test_battle" time="0.000">
<error type="ImportError">ImportError: Failed to import test module: test_battle
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/ryannguyen/fit-1008-group-30/tests/test_battle.py", line 4, in &lt;module>
    from pokemon import Charizard, Charmander, Eevee, Gastly, Squirtle, Venusaur
  File "/Users/ryannguyen/fit-1008-group-30/pokemon.py", line 10
    lost_hp = (12 + 1 * self.level) - self.hp
    ^^^^^^^
IndentationError: expected an indented block after function definition on line 8

</error>
</testcase>
<testcase classname="unittest.loader._FailedTest" name="test_poke_team" time="0.000">
<error type="ImportError">ImportError: Failed to import test module: test_poke_team
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/ryannguyen/fit-1008-group-30/tests/test_poke_team.py", line 3, in &lt;module>
    from pokemon import Bulbasaur, Charizard, Charmander, Gastly, Squirtle, Eevee
  File "/Users/ryannguyen/fit-1008-group-30/pokemon.py", line 10
    lost_hp = (12 + 1 * self.level) - self.hp
    ^^^^^^^
IndentationError: expected an indented block after function definition on line 8

</error>
</testcase>
<testcase classname="unittest.loader._FailedTest" name="test_pokemon" time="0.000">
<error type="ImportError">ImportError: Failed to import test module: test_pokemon
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/ryannguyen/fit-1008-group-30/tests/test_pokemon.py", line 1, in &lt;module>
    from pokemon import Venusaur
  File "/Users/ryannguyen/fit-1008-group-30/pokemon.py", line 10
    lost_hp = (12 + 1 * self.level) - self.hp
    ^^^^^^^
IndentationError: expected an indented block after function definition on line 8

</error>
</testcase>
<testcase classname="unittest.loader._FailedTest" name="test_pokemon_base" time="0.000">
<error type="ImportError">ImportError: Failed to import test module: test_pokemon_base
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/ryannguyen/fit-1008-group-30/tests/test_pokemon_base.py", line 3, in &lt;module>
    from pokemon import Eevee, Gastly, Haunter
  File "/Users/ryannguyen/fit-1008-group-30/pokemon.py", line 10
    lost_hp = (12 + 1 * self.level) - self.hp
    ^^^^^^^
IndentationError: expected an indented block after function definition on line 8

</error>
</testcase>
<testcase classname="unittest.loader._FailedTest" name="test_tournament" time="0.000">
<error type="ImportError">ImportError: Failed to import test module: test_tournament
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/ryannguyen/fit-1008-group-30/tests/test_tournament.py", line 2, in &lt;module>
    from tournament import Tournament
  File "/Users/ryannguyen/fit-1008-group-30/tournament.py", line 9, in &lt;module>
    from linked_list import LinkedList
ModuleNotFoundError: No module named 'linked_list'

</error>
</testcase>
<testcase classname="test_tower.TestTower" name="test_creation" time="0.001">
<error type="NotImplementedError">Traceback (most recent call last):
  File "/Users/ryannguyen/fit-1008-group-30/tests/base_test.py", line 47, in _callTestMethod
    raise e
  File "/Users/ryannguyen/fit-1008-group-30/tests/base_test.py", line 42, in _callTestMethod
    method()
  File "/Users/ryannguyen/fit-1008-group-30/tests/test_tower.py", line 11, in test_creation
    bt = BattleTower(Battle(verbosity=0))
  File "/Users/ryannguyen/fit-1008-group-30/battle.py", line 12, in __init__
    raise NotImplementedError()
NotImplementedError
</error>
</testcase>
<testcase classname="test_tower.TestTower" name="test_duplicates" time="0.000">
<error type="NotImplementedError">Traceback (most recent call last):
  File "/Users/ryannguyen/fit-1008-group-30/tests/base_test.py", line 47, in _callTestMethod
    raise e
  File "/Users/ryannguyen/fit-1008-group-30/tests/base_test.py", line 42, in _callTestMethod
    method()
  File "/Users/ryannguyen/fit-1008-group-30/tests/test_tower.py", line 32, in test_duplicates
    bt = BattleTower(Battle(verbosity=0))
  File "/Users/ryannguyen/fit-1008-group-30/battle.py", line 12, in __init__
    raise NotImplementedError()
NotImplementedError
</error>
</testcase>
<testcase classname="test_tower.TestTower" name="test_sort_lives" time="0.000">
<error type="NotImplementedError">Traceback (most recent call last):
  File "/Users/ryannguyen/fit-1008-group-30/tests/base_test.py", line 47, in _callTestMethod
    raise e
  File "/Users/ryannguyen/fit-1008-group-30/tests/base_test.py", line 42, in _callTestMethod
    method()
  File "/Users/ryannguyen/fit-1008-group-30/tests/test_tower.py", line 68, in test_sort_lives
    bt = BattleTower(Battle(verbosity=0))
  File "/Users/ryannguyen/fit-1008-group-30/battle.py", line 12, in __init__
    raise NotImplementedError()
NotImplementedError
</error>
</testcase>
</testsuite>
